'use client';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { cards, methods, questions, type LessonTwoActivities } from '@/lib/lesson-two';

type Props = { step: number; activities: LessonTwoActivities; update: (patch: Partial<LessonTwoActivities>) => void; reflection: string; setReflection: (value: string) => void };
export function LessonTwoContent({ step, activities: a, update, reflection, setReflection }: Props) {
  const [method, setMethod] = useState(0);
  const [output, setOutput] = useState<number | null>(null);
  function run(i: number) {
    const count = i === 0 ? a.textCount : i === 1 ? a.blockCount : a.aiSpecific ? 3 : 1;
    setOutput(count);
    if (count === 3) update({ runs: a.runs.map((v, j) => j === i ? true : v) });
  }
  if (step === 1) return <div className="mt-6 space-y-6">
    <p className="leading-8">친구에게 인사를 세 번 보여 주는 프로그램을 만들려고 해요. 코드를 직접 쓰거나, 명령 블록을 연결하거나, AI에게 만들어 달라고 요청할 수 있어요.</p>
    <div className="rounded-2xl bg-secondary p-5"><p className="font-black">오늘의 질문</p><p className="mt-2 leading-7">AI가 코드를 만들어 준다면, 사람은 어떤 일을 해야 할까요?</p></div>
    <fieldset className="space-y-3"><legend className="mb-3 font-bold">지금 생각과 가장 가까운 답을 골라 보세요.</legend>{['AI가 만들었으니 그대로 사용하면 돼요.', '목표를 설명하고 결과가 맞는지 확인해야 해요.', '아직 잘 모르겠어요. 직접 비교해 보고 싶어요.'].map((s, i) => <label key={s} className="flex cursor-pointer items-start gap-3 rounded-xl border p-4 leading-7"><input className="mt-2" type="radio" name="opening" checked={a.opening === i} onChange={() => update({ opening: i })} />{s}</label>)}</fieldset>
    {a.opening !== null && <p className="rounded-xl bg-muted p-4 leading-7">생각을 기록했어요. 같은 목표를 세 가지 방식으로 해결해 보고, 생각이 달라졌는지 살펴봐요.</p>}
    <p className="text-sm leading-6 text-muted-foreground">이 수업에서 ‘전통적인 코딩’은 사람이 텍스트나 블록으로 명령을 직접 구성하는 방식을 뜻해요. 실제 개발에서는 AI의 도움과 직접 코딩을 함께 쓰기도 해요.</p>
  </div>;
  if (step === 2) return <div className="mt-6 space-y-5">
    <p className="leading-7">각 방법으로 실행한 뒤, 인사가 <strong>정확히 세 줄</strong> 나오도록 수정해요. 세 가지 방법을 모두 성공시키세요.</p>
    <Tabs value={method} onValueChange={v => { setMethod(Number(v)); setOutput(null); }}><TabsList className="!h-auto w-full flex-wrap p-1">{methods.map((m, i) => <TabsTrigger key={m} value={i} className="min-h-11 px-3">{m}{a.runs[i] ? ' ✓' : ''}</TabsTrigger>)}</TabsList>
      {methods.map((m, i) => <TabsContent key={m} value={i} className="pt-4 text-base"><div className="rounded-2xl border p-5">
        <h3 className="font-black">{['코드의 숫자를 직접 바꿔요', '명령 블록의 반복 횟수를 바꿔요', '원하는 결과를 말로 설명해요'][i]}</h3>
        <p className="mt-2 leading-7 text-muted-foreground">{['Python 코드 예시예요. range의 숫자만큼 들여쓴 명령을 반복해요.', '「반복하기」 안의 「말하기」 명령을 정해진 횟수만큼 실행해요.', '두 요청을 비교해 보세요. 어떤 요청에 목표가 더 분명하게 담겨 있나요?'][i]}</p>
        {i < 2 ? <><fieldset className="my-4 flex flex-wrap gap-3"><legend className="mb-2 font-bold">반복 횟수</legend>{[1, 2, 3].map(n => <label key={n} className="flex items-center gap-2 rounded-lg border px-4 py-2"><input type="radio" name={`count-${i}`} checked={(i === 0 ? a.textCount : a.blockCount) === n} onChange={() => { setOutput(null); update(i === 0 ? { textCount: n } : { blockCount: n }); }} />{n}번</label>)}</fieldset>{i === 0 ? <pre className="overflow-x-auto rounded-xl bg-slate-900 p-5 text-base leading-8 text-slate-100"><code>{`for i in range(${a.textCount}):\n    print("안녕!")`}</code></pre> : <div className="rounded-xl border-2 border-amber-500 bg-amber-50 p-4 font-bold text-amber-950"><p>{a.blockCount}번 반복하기</p><div className="ml-4 mt-3 rounded-lg border-2 border-purple-400 bg-purple-100 p-3 text-purple-950">“안녕!” 말하기</div></div>}</> : <fieldset className="mt-4 space-y-3"><legend className="font-bold">AI에게 보낼 요청 선택</legend>{['인사하는 프로그램을 만들어 줘.', '“안녕!”을 한 줄에 한 번씩, 정확히 세 줄 보여 주는 프로그램을 만들어 줘.'].map((s, j) => <label key={s} className="flex items-start gap-3 rounded-xl border p-4 leading-7"><input className="mt-2" type="radio" name="ai-request" checked={a.aiSpecific === (j === 1)} onChange={() => { setOutput(null); update({ aiSpecific: j === 1 }); }} />{s}</label>)}</fieldset>}
        <Button className="mt-5" onClick={() => run(i)}>{i === 2 ? '예시 결과 확인' : '실행하기'}</Button>
        <p className="mt-3 text-sm leading-6 text-muted-foreground">{i === 2 ? '수업용 시뮬레이션이에요. 실제 AI에 요청하지 않으며 준비된 결과를 보여 줘요. 실제 AI의 결과는 달라질 수 있어요.' : '정해진 코드·블록의 동작을 보여 주는 수업용 시뮬레이션이에요.'}</p>
      </div></TabsContent>)}
    </Tabs>
    {output !== null && <div role="status" className="rounded-2xl border-2 border-primary bg-secondary/40 p-5"><h3 className="font-black">{methods[method]} 실행 결과 · {output}줄</h3><div className="my-3 rounded-xl bg-card p-4 font-mono leading-8">{Array.from({ length: output }, (_, i) => <div key={i}>안녕!</div>)}</div><p className="leading-7">{output === 3 ? '목표와 같아요! 다른 방법도 체험해 보세요.' : '목표는 세 줄이에요. 반복 횟수나 요청을 수정한 뒤 다시 실행해 보세요.'}</p></div>}
    <p className="font-bold">체험 성공: {a.runs.filter(Boolean).length} / 3</p>
    <div className="rounded-xl bg-muted p-4 leading-7">표현 방법은 달라도 <strong>반복할 내용과 횟수</strong>가 필요해요. AI 코딩에서도 사람이 목표를 정하고 결과를 확인해요.</div>
  </div>;
  if (step === 3) return <div className="mt-6 space-y-5"><p className="leading-7">각 사례에서 사용한 코딩 방법을 골라 보세요. 틀려도 설명을 읽고 다시 도전할 수 있어요.</p>{cards.map((c, i) => <fieldset key={c.text} className="rounded-2xl border p-4"><legend className="px-1 font-bold">사례 {i + 1}</legend><p className="mb-4 leading-7">{c.text}</p><div className="flex flex-wrap gap-3">{methods.map((m, j) => <label key={m} className="flex cursor-pointer items-center gap-2 rounded-lg border px-3 py-2"><input type="radio" name={`card-${i}`} checked={a.classifications[i] === j} onChange={() => update({ classifications: a.classifications.map((v, k) => k === i ? j : v), classificationChecked: false })} />{m}</label>)}</div>{a.classificationChecked && <p className="mt-4 leading-7 text-primary">{a.classifications[i] === c.answer ? '정답이에요. ' : '다시 살펴봐요. '}{c.tip}</p>}</fieldset>)}<Button disabled={a.classifications.some(v => v === null)} onClick={() => update({ classificationChecked: true })}>분류 결과 확인</Button>{a.classificationChecked && <p role="status" className="font-bold">{cards.filter((c, i) => a.classifications[i] === c.answer).length} / {cards.length}개 정답</p>}</div>;
  if (step === 4) return <div className="mt-6 space-y-6"><p className="leading-7">체험한 내용을 바탕으로 ‘어떻게 명령하는지’와 ‘사람이 무엇을 하는지’를 방법마다 한 문장 이상 써 보세요.</p><div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[480px] text-left text-base leading-7"><caption className="sr-only">코딩 방식의 명령 방법과 수정 방법 비교</caption><thead className="bg-secondary"><tr><th className="p-3">방법</th><th className="p-3">명령하기</th><th className="p-3">수정하기</th></tr></thead><tbody>{methods.map((m, i) => <tr key={m} className="border-t"><th className="p-3">{m}</th><td className="p-3">{['문법에 맞는 코드를 작성', '명령 블록을 연결', '자연어로 목표와 조건 설명'][i]}</td><td className="p-3">{['코드의 숫자나 명령 수정', '블록의 값이나 연결 수정', '문제를 설명해 수정 요청 후 확인'][i]}</td></tr>)}</tbody></table></div>{methods.map((m, i) => <div key={m}><label htmlFor={`comparison-${i}`} className="font-black">{m} — 나의 비교 문장</label><Textarea id={`comparison-${i}`} className="mt-2 min-h-28 text-base md:text-base" maxLength={300} value={a.comparison[i]} placeholder="명령하는 방법과 사람이 하는 일을 연결해 써 보세요." onChange={e => update({ comparison: a.comparison.map((s, j) => j === i ? e.target.value : s) })} /><p className="mt-1 text-sm text-muted-foreground">{a.comparison[i].trim().length} / 300자 · 10자 이상</p></div>)}<p className="rounded-xl bg-secondary p-4 leading-7"><strong>공통점:</strong> 세 방법 모두 사람이 목표를 정하고 결과를 확인하며 수정해요. AI 코딩이 언제나 가장 좋거나 다른 방법이 필요 없어지는 것은 아니에요.</p></div>;
  return <div className="mt-6 space-y-6">{questions.map((q, i) => <fieldset key={q.title} className="rounded-2xl border p-4"><legend className="px-1 font-bold">퀴즈 {i + 1}</legend><p className="mb-3 font-bold leading-7">{q.title}</p><div className="space-y-3">{q.options.map((s, j) => <label key={s} className="flex cursor-pointer items-start gap-3 rounded-lg bg-muted/60 p-3 leading-7"><input className="mt-2" type="radio" name={`quiz-${i}`} checked={a.answers[i] === j} onChange={() => update({ answers: a.answers.map((v, k) => k === i ? j : v), quizChecked: false })} />{s}</label>)}</div>{a.quizChecked && <p className="mt-3 leading-7 text-primary">{a.answers[i] === q.answer ? '정답이에요! ' : '다시 생각해 봐요. '}{q.tip}</p>}</fieldset>)}<Button disabled={a.answers.some(v => v === null)} onClick={() => update({ quizChecked: true })}>퀴즈 확인</Button>{a.quizChecked && <p role="status" className="font-bold">{questions.filter((q, i) => a.answers[i] === q.answer).length} / 3문항 정답</p>}<div><label htmlFor="reflection" className="font-black">오늘의 성찰</label><p className="my-2 leading-7">AI가 코드를 만들어 주어도 사람이 해야 할 일은 무엇인가요? 오늘 체험한 예를 넣어 써 보세요.</p><Textarea id="reflection" className="min-h-32 text-base md:text-base" maxLength={1000} value={reflection} onChange={e => setReflection(e.target.value)} /><p className="mt-1 text-sm text-muted-foreground">{reflection.trim().length} / 1000자 · 10자 이상</p></div></div>;
}
