'use client';

import { CanvaWorkflow, LessonSchedule } from '@/components/lesson-workflow';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { flowOptions, promptIsSafe, questions, testChecks, type LessonSixActivities } from '@/lib/lesson-six';

type Props = { step: number; activities: LessonSixActivities; update: (patch: Partial<LessonSixActivities>) => void; reflection: string; setReflection: (value: string) => void };

function RadioCards({ name, options, value, onChange }: { name: string; options: string[]; value: number | null; onChange: (value: number) => void }) {
  return <div className="space-y-3">{options.map((text, i) => <label key={text} className="flex cursor-pointer items-start gap-3 rounded-xl border p-4 leading-7"><input className="mt-2" type="radio" name={name} checked={value === i} onChange={() => onChange(i)} />{text}</label>)}</div>;
}

export function LessonSixContent({ step, activities: a, update, reflection, setReflection }: Props) {
  if (step === 1) return <div className="mt-6 space-y-6"><p className="leading-8">앱을 처음 만들 때는 한 번에 많은 일을 시키기보다, 사용자가 한 행동에 앱이 한 가지 도움을 주는 기능부터 만들어요. 그래야 쉽게 확인하고 고칠 수 있어요. 5차시가 첫 앱 만들기였다면, 오늘은 내 앱의 한 기능을 입력·처리·결과로 설명하고 시험해요.</p><LessonSchedule>도입 3 + 입력·처리·결과 5 + 지시 5 + Canva 원본 열기·적용 대기 5 + 자기 앱 시험 5 + 수정·대기·재시험 7 + 웹 복귀 2 + 퀴즈·성찰 5 + 저장·정리·여유 3 = 40분. 교사는 한 버튼의 입력·처리·결과를 시범으로 구별해요. 원본 재사용 기준이며 새 생성은 시간이 더 필요해요. 30분에 외부 작업을 마무리하거나 남은 일을 적고 돌아와요.</LessonSchedule><fieldset><legend className="mb-3 font-bold">‘한 기능 앱’의 설명으로 가장 알맞은 것은?</legend><RadioCards name="concept" value={a.conceptChoice} onChange={conceptChoice => update({ conceptChoice, conceptChecked: false })} options={['한 가지 중요한 일을 분명하게 해 보는 작은 앱이에요.', '처음부터 모든 기능을 다 넣은 앱이에요.', '개인정보를 많이 모으는 앱이에요.']} /></fieldset><Button disabled={a.conceptChoice === null} onClick={() => update({ conceptChecked: true })}>확인하기</Button>{a.conceptChecked && <output className="block rounded-xl bg-secondary p-4 leading-7">{a.conceptChoice === 0 ? '정답이에요! 한 가지 동작을 먼저 만들면 앱의 흐름을 살피고 고치기 쉬워요.' : '다시 생각해 봐요. 처음에는 가장 중요한 한 가지 도움을 주는 기능부터 만들어요.'}</output>}</div>;
  if (step === 2) return <div className="mt-6 space-y-6"><p className="leading-7">입력은 사용자가 하는 행동, 처리는 앱이 고르거나 계산하는 일, 결과는 화면에 보이는 내용이에요. 버튼 누르기도 입력이에요.</p><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-secondary/60 p-4 leading-7"><p className="font-bold">입력</p><p>사용자가 추천 버튼 누르기</p></div><div className="rounded-xl bg-secondary/60 p-4 leading-7"><p className="font-bold">처리</p><p>앱이 놀이 목록에서 한 놀이와 맞는 준비물 고르기</p></div><div className="rounded-xl bg-secondary/60 p-4 leading-7"><p className="font-bold">결과</p><p>고른 놀이 이름·준비물 카드 표시하기</p></div></div><fieldset><legend className="mb-3 font-black">1. 사용자가 하는 입력은?</legend><RadioCards name="input" options={flowOptions.inputs} value={a.inputChoice} onChange={inputChoice => update({ inputChoice, flowChecked: false })} /></fieldset><fieldset><legend className="mb-3 font-black">2. 앱이 하는 전체 동작은?</legend><RadioCards name="action" options={flowOptions.actions} value={a.actionChoice} onChange={actionChoice => update({ actionChoice, flowChecked: false })} /></fieldset><fieldset><legend className="mb-3 font-black">3. 사용자에게 보여 줄 결과는?</legend><RadioCards name="output" options={flowOptions.outputs} value={a.outputChoice} onChange={outputChoice => update({ outputChoice, flowChecked: false })} /></fieldset><Button disabled={a.inputChoice === null || a.actionChoice === null || a.outputChoice === null} onClick={() => update({ flowChecked: true })}>한 기능 흐름 확인</Button>{a.flowChecked && <output className="block rounded-xl bg-secondary p-4 leading-7">{a.inputChoice === 0 && a.actionChoice === 0 && a.outputChoice === 0 ? '선택한 전체 동작에는 처리와 표시가 함께 들어 있어요. 처리 = 놀이·준비물 고르기, 결과 = 고른 내용을 카드로 보여 주기예요. 짝에게 두 부분을 나누어 설명해요.' : '입력은 사용자 행동이에요. 앱은 놀이와 준비물을 고른 뒤 결과를 보여 줘야 해요. 개인정보 수집이나 광고는 이 문제를 해결하는 동작이 아니에요.'}</output>}</div>;
  if (step === 3) return <div className="mt-6 space-y-5"><p className="leading-7">5차시의 놀이·준비물 추천 원본이 있으면 한 기능만 다듬어요. 다른 주제의 앱이거나 원본이 없다면 기존 작품을 보존하고 Canva에서 놀이 추천 앱을 새로 만들어요. 추가 대기 시간이 필요할 수 있어요. 공유 실행 URL만으로는 수정할 수 없어요. 이전 글을 직접 참고하되 지금 쓴 글을 덮어쓰지 않아요. 누가 쓰는지, 버튼을 누르면 무엇을 하는지, 결과를 어떻게 보여 줄지를 넣고 개인정보는 쓰지 않아요.</p><div className="rounded-2xl bg-secondary/60 p-4 leading-7"><p className="font-bold">안전한 예시</p><p className="mt-2">“추천 버튼을 누르면 목록에서 놀이 한 가지와 맞는 준비물을 골라 큰 글씨 카드로 보여 줘. 전화번호를 받지 않게 해 줘.” · 틀: “__가 __하면 앱이 __를 골라 __로 보여 줘.”</p></div><label htmlFor="ownPrompt" className="font-black">나의 한 기능 제작 지시</label><Textarea id="ownPrompt" className="min-h-36 text-base md:text-base" maxLength={1000} value={a.ownPrompt} onChange={e => update({ ownPrompt: e.target.value, promptChecked: false })} /><p className="text-sm text-muted-foreground">{a.ownPrompt.trim().length} / 1000자 · 35자 이상 · 이름, 전화번호, 주소, 비밀번호를 쓰지 않아요.</p><Button disabled={a.ownPrompt.trim().length < 35} onClick={() => update({ promptChecked: true })}>안전한 지시 확인</Button>{a.promptChecked && <output className="block rounded-xl bg-secondary p-4 leading-7">{promptIsSafe(a.ownPrompt) ? '길이와 일부 개인정보 형태를 확인했어요. 한 입력·처리·결과가 지시에 들어 있는지, 실제 개인정보가 없는지 직접 읽어 확인해요.' : '개인정보 형태나 요구로 보이는 내용을 고쳐요. 실제 값은 넣지 말고 “전화번호를 받지 않게”처럼 안전한 조건을 써요. 자동 확인의 한계는 교사와 함께 살펴요.'}</output>}<CanvaWorkflow><ol className="mt-3 list-decimal space-y-2 pl-5"><li>지시를 원본 Canva 프로젝트의 AI 코드 대화에 붙여 넣어 적용해요. 놀이·준비물 추천 원본이 없으면 새 생성으로 시작해요.</li><li>기다리는 동안 “__를 누르면 __가 나올 것”이라고 짝에게 예상해요.</li><li>웹 4단계의 점검 항목을 읽고 자기 앱을 시험해요.</li></ol></CanvaWorkflow></div>;
  if (step === 4) return <div className="mt-6 space-y-6"><p className="leading-7">내 Canva 앱에서 추천 버튼을 직접 눌러 놀이와 준비물의 짝이 맞는지 봐요. 짝에게 입력·처리·결과와 예상/실제를 설명해요. 실패를 발견해도 직접 점검했다면 체크해요. 예시만 읽었거나 시연만 봤다면 직접 시험한 체크는 하지 않아요.</p><details className="rounded-xl border p-4 leading-7"><summary className="cursor-pointer font-bold">참고·오류 때 보는 한 기능 예시</summary><p className="mt-2">버튼을 누르면 “보물찾기 / 종이와 연필”이 나오는 준비 예시예요. 실제 내 앱 결과가 아니에요. 글자가 작다면 글자 크기를 고칠 수 있어요. 일시 오류 때는 이미 만든 자기 앱부터 열고, 실제로 못 한 시험은 남겨 둬요.</p></details><fieldset><legend className="mb-3 font-black">이 결과를 어떻게 판단할까요?</legend><RadioCards name="result" value={a.resultChoice} onChange={resultChoice => update({ resultChoice, testChecked: false })} options={['화면이 보이니 확인하지 않고 바로 제출해요.', '버튼, 결과, 읽기 쉬운 안내와 안전한 입력을 직접 확인해요.']} /></fieldset><div className="space-y-3">{testChecks.map((text, i) => <label key={text} className="flex cursor-pointer items-start gap-3 rounded-xl border p-4 leading-7"><input className="mt-2" type="checkbox" checked={a.testChoices[i]} onChange={e => update({ testChoices: a.testChoices.map((value, index) => index === i ? e.target.checked : value), testChecked: false })} />{text}</label>)}</div><label htmlFor="revisionPrompt" className="font-black">수정 지시</label><Textarea id="revisionPrompt" className="min-h-28 text-base md:text-base" maxLength={1000} value={a.revisionPrompt} onChange={e => update({ revisionPrompt: e.target.value, testChecked: false })} placeholder="__를 눌렀더니 __였어요. __를 __로 고쳐 주세요." /><p className="text-sm text-muted-foreground">{a.revisionPrompt.trim().length} / 1000자 · 15자 이상</p><CanvaWorkflow><ol className="mt-3 list-decimal space-y-2 pl-5"><li>관찰을 근거로 수정 지시 한 가지를 Canva 원본 대화에 보내요.</li><li>같은 버튼·순서로 다시 시험해요. 빠른 학생은 두 번 눌러 놀이·준비물 짝도 비교해요.</li><li>웹에 돌아와 점검 기록을 확인하고 성찰에 예상·실제·수정 뒤 또는 미반영을 적어요.</li></ol></CanvaWorkflow><Button disabled={a.resultChoice === null || !a.testChoices.every(Boolean) || a.revisionPrompt.trim().length < 15} onClick={() => update({ testChecked: true })}>테스트와 수정 계획 확인</Button>{a.testChecked && <output className="block rounded-xl bg-secondary p-4 leading-7">{a.resultChoice === 1 ? '점검 체크와 수정문을 기록했어요. 동작 성공을 자동 인증한 것은 아니에요. 수정 뒤 결과와 남은 실패도 사실대로 기록해요.' : '결과가 보여도 꼭 직접 테스트해야 해요. 다시 선택해 보세요.'}</output>}</div>;
  return <div className="mt-6 space-y-6">{questions.map((q, i) => <fieldset key={q.title} className="rounded-2xl border p-4"><legend className="px-1 font-bold">퀴즈 {i + 1}</legend><p className="mb-3 font-bold leading-7">{q.title}</p><RadioCards name={`quiz-${i}`} options={q.options} value={a.answers[i]} onChange={answer => update({ answers: a.answers.map((value, index) => index === i ? answer : value), quizChecked: false })} />{a.quizChecked && <p className="mt-3 rounded-xl bg-secondary p-3 leading-7">{a.answers[i] === q.answer ? '정답이에요! ' : '다시 생각해 봐요. '}{q.tip}</p>}</fieldset>)}<Button disabled={a.answers.some(value => value === null)} onClick={() => update({ quizChecked: true })}>퀴즈 확인</Button>{a.quizChecked && <output className="block font-bold">{questions.filter((q, i) => a.answers[i] === q.answer).length} / 3문항 정답</output>}<div><label htmlFor="reflection" className="font-black">오늘의 성찰</label><p className="my-2 leading-7">입력 __ → 처리 __ → 결과 __. 예상 __, 실제 __, 수정 뒤 __/아직 안 된 점 __. 한 번의 관찰을 근거로 쓰고 실제로 못 한 부분은 그대로 적어요.</p><Textarea id="reflection" className="min-h-28 text-base md:text-base" maxLength={1000} value={reflection} onChange={e => setReflection(e.target.value)} /><p className="mt-1 text-sm text-muted-foreground">{reflection.trim().length} / 1000자 · 10자 이상</p></div></div>;
}
