'use client';

import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { flowOptions, promptIsSafe, questions, testChecks, type LessonSixActivities } from '@/lib/lesson-six';

type Props = { step: number; activities: LessonSixActivities; update: (patch: Partial<LessonSixActivities>) => void; reflection: string; setReflection: (value: string) => void };

function RadioCards({ name, options, value, onChange }: { name: string; options: string[]; value: number | null; onChange: (value: number) => void }) {
  return <div className="space-y-3">{options.map((text, i) => <label key={text} className="flex cursor-pointer items-start gap-3 rounded-xl border p-4 leading-7"><input className="mt-2" type="radio" name={name} checked={value === i} onChange={() => onChange(i)} />{text}</label>)}</div>;
}

export function LessonSixContent({ step, activities: a, update, reflection, setReflection }: Props) {
  if (step === 1) return <div className="mt-6 space-y-6"><p className="leading-8">앱을 처음 만들 때는 한 번에 많은 일을 시키기보다, 사용자가 한 행동에 앱이 한 가지 도움을 주는 기능부터 만들어요. 그래야 쉽게 확인하고 고칠 수 있어요.</p><fieldset><legend className="mb-3 font-bold">‘한 기능 앱’의 설명으로 가장 알맞은 것은?</legend><RadioCards name="concept" value={a.conceptChoice} onChange={conceptChoice => update({ conceptChoice, conceptChecked: false })} options={['한 가지 중요한 일을 분명하게 해 보는 작은 앱이에요.', '처음부터 모든 기능을 다 넣은 앱이에요.', '개인정보를 많이 모으는 앱이에요.']} /></fieldset><Button disabled={a.conceptChoice === null} onClick={() => update({ conceptChecked: true })}>확인하기</Button>{a.conceptChecked && <p role="status" className="rounded-xl bg-secondary p-4 leading-7">{a.conceptChoice === 0 ? '정답이에요! 한 가지 동작을 먼저 만들면 앱의 흐름을 살피고 고치기 쉬워요.' : '다시 생각해 봐요. 처음에는 가장 중요한 한 가지 도움을 주는 기능부터 만들어요.'}</p>}</div>;
  if (step === 2) return <div className="mt-6 space-y-6"><p className="leading-7">한 기능 앱은 ‘입력 → 동작 → 결과’로 생각할 수 있어요. 쉬는 시간 놀이 추천 앱의 한 가지 기능을 아래에서 골라 완성해 보세요.</p><fieldset><legend className="mb-3 font-black">1. 사용자가 하는 입력은?</legend><RadioCards name="input" options={flowOptions.inputs} value={a.inputChoice} onChange={inputChoice => update({ inputChoice, flowChecked: false })} /></fieldset><fieldset><legend className="mb-3 font-black">2. 앱이 하는 동작은?</legend><RadioCards name="action" options={flowOptions.actions} value={a.actionChoice} onChange={actionChoice => update({ actionChoice, flowChecked: false })} /></fieldset><fieldset><legend className="mb-3 font-black">3. 사용자에게 보여 줄 결과는?</legend><RadioCards name="output" options={flowOptions.outputs} value={a.outputChoice} onChange={outputChoice => update({ outputChoice, flowChecked: false })} /></fieldset><Button disabled={a.inputChoice === null || a.actionChoice === null || a.outputChoice === null} onClick={() => update({ flowChecked: true })}>한 기능 흐름 확인</Button>{a.flowChecked && <p role="status" className="rounded-xl bg-secondary p-4 leading-7">{a.inputChoice === 0 && a.actionChoice === 0 && a.outputChoice === 0 ? '흐름이 완성됐어요. 버튼을 누르면 앱이 추천을 고르고, 읽기 쉬운 결과를 보여 줘요.' : '한 기능은 안전하고 분명한 입력, 도움이 되는 동작, 알아보기 쉬운 결과로 이어져야 해요.'}</p>}</div>;
  if (step === 3) return <div className="mt-6 space-y-5"><p className="leading-7">한 기능만 또렷하게 만드는 제작 지시를 써 보세요. 누가 쓰는지, 버튼을 누르면 무엇을 하는지, 결과를 어떻게 보여 줄지를 넣고 개인정보는 쓰지 않아요.</p><div className="rounded-2xl bg-secondary/60 p-4 leading-7"><p className="font-bold">안전한 예시</p><p className="mt-2">“6학년 친구가 쉬는 시간 놀이를 고르는 앱을 만들어 줘. 추천 버튼을 누르면 놀이 이름과 준비물을 큰 글씨 카드로 보여 주는 한 가지 기능을 만들어 줘.”</p></div><label htmlFor="ownPrompt" className="font-black">나의 한 기능 제작 지시</label><Textarea id="ownPrompt" className="min-h-36 text-base md:text-base" maxLength={1000} value={a.ownPrompt} onChange={e => update({ ownPrompt: e.target.value, promptChecked: false })} /><p className="text-sm text-muted-foreground">{a.ownPrompt.trim().length} / 1000자 · 35자 이상 · 이름, 전화번호, 주소, 비밀번호를 쓰지 않아요.</p><Button disabled={a.ownPrompt.trim().length < 35} onClick={() => update({ promptChecked: true })}>안전한 지시 확인</Button>{a.promptChecked && <p role="status" className="rounded-xl bg-secondary p-4 leading-7">{promptIsSafe(a.ownPrompt) ? '좋아요! 한 가지 기능을 안전하고 구체적으로 설명했어요.' : '개인정보처럼 보이는 내용이 있어요. 이름·전화번호·주소·비밀번호 없이 일반적인 조건으로 고쳐 보세요.'}</p>}</div>;
  if (step === 4) return <div className="mt-6 space-y-6"><p className="leading-7">실제 Canva AI를 부르지 않아도 괜찮아요. 아래는 한 기능 제작 지시로 만들어졌다고 가정한 준비된 앱이에요. 직접 써 본다고 생각하고 고칠 점을 찾아 보세요.</p><div className="rounded-2xl border-2 border-dashed p-5"><p className="font-black">준비된 결과: 놀이 추천 한 기능 앱</p><div className="mt-4 rounded-xl bg-muted p-4"><p className="text-lg font-bold">오늘의 놀이를 골라 볼까요?</p><Button className="mt-4" variant="outline">놀이 추천 받기</Button><p className="mt-4 rounded-lg bg-background p-3 leading-7">추천: 보물찾기<br />준비물: 종이와 연필</p><p className="mt-3 text-sm leading-6 text-muted-foreground">글자가 조금 작고, 처음 보는 친구에게는 버튼 설명이 더 필요해 보여요.</p></div></div><fieldset><legend className="mb-3 font-black">이 결과를 어떻게 판단할까요?</legend><RadioCards name="result" value={a.resultChoice} onChange={resultChoice => update({ resultChoice, testChecked: false })} options={['화면이 보이니 확인하지 않고 바로 제출해요.', '버튼, 결과, 읽기 쉬운 안내와 안전한 입력을 직접 확인해요.']} /></fieldset><div className="space-y-3">{testChecks.map((text, i) => <label key={text} className="flex cursor-pointer items-start gap-3 rounded-xl border p-4 leading-7"><input className="mt-2" type="checkbox" checked={a.testChoices[i]} onChange={e => update({ testChoices: a.testChoices.map((value, index) => index === i ? e.target.checked : value), testChecked: false })} />{text}</label>)}</div><label htmlFor="revisionPrompt" className="font-black">수정 지시</label><Textarea id="revisionPrompt" className="min-h-28 text-base md:text-base" maxLength={1000} value={a.revisionPrompt} onChange={e => update({ revisionPrompt: e.target.value, testChecked: false })} placeholder="예: 버튼 설명과 결과 글자를 더 크게 하고, 준비물을 목록으로 보여 줘." /><p className="text-sm text-muted-foreground">{a.revisionPrompt.trim().length} / 1000자 · 15자 이상</p><Button disabled={a.resultChoice === null || !a.testChoices.every(Boolean) || a.revisionPrompt.trim().length < 15} onClick={() => update({ testChecked: true })}>테스트와 수정 계획 확인</Button>{a.testChecked && <p role="status" className="rounded-xl bg-secondary p-4 leading-7">{a.resultChoice === 1 ? '테스트 계획을 확인했어요. 한 기능이 정확히 동작하는지 확인하고, 불편한 점을 구체적으로 고치는 것이 중요해요.' : '결과가 보여도 꼭 직접 테스트해야 해요. 다시 선택해 보세요.'}</p>}</div>;
  return <div className="mt-6 space-y-6">{questions.map((q, i) => <fieldset key={q.title} className="rounded-2xl border p-4"><legend className="px-1 font-bold">퀴즈 {i + 1}</legend><p className="mb-3 font-bold leading-7">{q.title}</p><RadioCards name={`quiz-${i}`} options={q.options} value={a.answers[i]} onChange={answer => update({ answers: a.answers.map((value, index) => index === i ? answer : value), quizChecked: false })} />{a.quizChecked && <p className="mt-3 rounded-xl bg-secondary p-3 leading-7">{a.answers[i] === q.answer ? '정답이에요! ' : '다시 생각해 봐요. '}{q.tip}</p>}</fieldset>)}<Button disabled={a.answers.some(value => value === null)} onClick={() => update({ quizChecked: true })}>퀴즈 확인</Button>{a.quizChecked && <p role="status" className="font-bold">{questions.filter((q, i) => a.answers[i] === q.answer).length} / 3문항 정답</p>}<div><label htmlFor="reflection" className="font-black">오늘의 성찰</label><p className="my-2 leading-7">내가 만든 한 기능 앱에서 꼭 확인하고 싶은 한 가지를 써 보세요.</p><Textarea id="reflection" className="min-h-28 text-base md:text-base" maxLength={1000} value={reflection} onChange={e => setReflection(e.target.value)} /><p className="mt-1 text-sm text-muted-foreground">{reflection.trim().length} / 1000자 · 10자 이상</p></div></div>;
}
