'use client';

import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { planOptions, promptIsSafe, questions, testChecks, type LessonFiveActivities } from '@/lib/lesson-five';

type Props = { step: number; activities: LessonFiveActivities; update: (patch: Partial<LessonFiveActivities>) => void; reflection: string; setReflection: (value: string) => void };

function RadioCards({ name, options, value, onChange }: { name: string; options: string[]; value: number | null; onChange: (value: number) => void }) {
  return <div className="space-y-3">{options.map((text, i) => <label key={text} className="flex cursor-pointer items-start gap-3 rounded-xl border p-4 leading-7"><input className="mt-2" type="radio" name={name} checked={value === i} onChange={() => onChange(i)} />{text}</label>)}</div>;
}

export function LessonFiveContent({ step, activities: a, update, reflection, setReflection }: Props) {
  if (step === 1) return <div className="mt-6 space-y-6"><p className="leading-8">Canva AI 코드는 글로 설명한 앱 아이디어를 바탕으로 화면과 간단한 기능을 만들어 보는 도구예요. 결과는 사람이 직접 테스트하고 고쳐야 해요.</p><fieldset><legend className="mb-3 font-bold">Canva AI 코드가 해 주는 일로 가장 알맞은 것은?</legend><RadioCards name="intro" value={a.introChoice} onChange={introChoice => update({ introChoice, introChecked: false })} options={['내 생각 없이 완벽한 앱을 대신 제출해 줘요.', '내가 쓴 제작 지시를 바탕으로 앱 화면과 기능 아이디어를 만들어 줘요.', '친구의 개인정보를 찾아서 앱에 넣어 줘요.']} /></fieldset><Button disabled={a.introChoice === null} onClick={() => update({ introChecked: true })}>확인하기</Button>{a.introChecked && <p role="status" className="rounded-xl bg-secondary p-4 leading-7">{a.introChoice === 1 ? '정답이에요! 내가 정한 목적과 지시를 바탕으로 결과를 만들고, 사람이 확인하며 고쳐 가요.' : '다시 생각해 봐요. Canva AI 코드는 내 아이디어를 바탕으로 화면과 기능을 만들어 보도록 도와줘요.'}</p>}</div>;
  if (step === 2) return <div className="mt-6 space-y-6"><p className="leading-7">좋은 앱은 누가 어떤 문제를 해결할지와 가장 중요한 기능을 먼저 정해요. 아래에서 하나씩 골라 제작 계획을 세워 보세요.</p><fieldset><legend className="mb-3 font-black">누가 사용할까요?</legend><RadioCards name="user" options={planOptions.users} value={a.userChoice} onChange={userChoice => update({ userChoice, planChecked: false })} /></fieldset><fieldset><legend className="mb-3 font-black">어떤 문제를 도울까요?</legend><RadioCards name="problem" options={planOptions.problems} value={a.problemChoice} onChange={problemChoice => update({ problemChoice, planChecked: false })} /></fieldset><fieldset><legend className="mb-3 font-black">가장 먼저 넣을 핵심 기능은?</legend><RadioCards name="feature" options={planOptions.features} value={a.featureChoice} onChange={featureChoice => update({ featureChoice, planChecked: false })} /></fieldset><Button disabled={a.userChoice === null || a.problemChoice === null || a.featureChoice === null} onClick={() => update({ planChecked: true })}>제작 계획 확인</Button>{a.planChecked && <p role="status" className="rounded-xl bg-secondary p-4 leading-7">계획이 준비됐어요. 한 번에 기능을 많이 넣기보다 가장 중요한 한 가지 기능부터 만들면 테스트하기 쉬워요.</p>}</div>;
  if (step === 3) return <div className="mt-6 space-y-5"><p className="leading-7">이제 제작 지시를 써 보세요. 목표, 사용할 사람, 핵심 기능, 화면 모양 중 두 가지 이상을 넣고 개인정보는 쓰지 않아요.</p><div className="rounded-2xl bg-secondary/60 p-4 leading-7"><p className="font-bold">안전한 예시</p><p className="mt-2">“6학년 친구가 쉬는 시간 놀이를 고를 수 있는 앱을 만들어 줘. 추천 버튼을 누르면 놀이 이름과 준비물을 큰 글씨 카드로 보여 줘.”</p></div><label htmlFor="ownPrompt" className="font-black">나의 제작 지시</label><Textarea id="ownPrompt" className="min-h-36 text-base md:text-base" maxLength={1000} value={a.ownPrompt} onChange={e => update({ ownPrompt: e.target.value, promptChecked: false })} /><p className="text-sm text-muted-foreground">{a.ownPrompt.trim().length} / 1000자 · 30자 이상 · 이름, 전화번호, 주소, 비밀번호를 쓰지 않아요.</p><Button disabled={a.ownPrompt.trim().length < 30} onClick={() => update({ promptChecked: true })}>안전한 지시 확인</Button>{a.promptChecked && <p role="status" className="rounded-xl bg-secondary p-4 leading-7">{promptIsSafe(a.ownPrompt) ? '좋아요! 구체적인 제작 지시를 안전하게 썼어요. 다음 단계에서 준비된 결과를 테스트해 보세요.' : '개인정보처럼 보이는 내용이 있어요. 이름·전화번호·주소·비밀번호 없이 일반적인 조건으로 고쳐 보세요.'}</p>}</div>;
  if (step === 4) return <div className="mt-6 space-y-6"><p className="leading-7">실제 Canva AI를 부르지 않아도 괜찮아요. 아래는 제작 지시로 만들어졌다고 가정한 준비된 결과예요. 사람의 눈으로 테스트하고 수정 지시를 써 보세요.</p><div className="rounded-2xl border-2 border-dashed p-5"><p className="font-black">준비된 결과: 쉬는 시간 놀이 추천 앱</p><div className="mt-4 rounded-xl bg-muted p-4"><p className="text-lg font-bold">오늘의 놀이: 보물찾기</p><p className="mt-2 leading-7">추천 버튼을 누르면 놀이 한 가지와 준비물을 보여 줍니다. 하지만 글자가 조금 작고 안내가 짧아요.</p><Button className="mt-4" variant="outline">추천 다시 보기</Button></div></div><fieldset><legend className="mb-3 font-black">이 결과를 어떻게 판단할까요?</legend><RadioCards name="result" value={a.resultChoice} onChange={resultChoice => update({ resultChoice, testChecked: false })} options={['화면이 보이니 확인하지 않고 바로 제출해요.', '버튼, 글자, 안전한 입력을 직접 확인하고 고칠 점을 찾아요.']} /></fieldset><div className="space-y-3">{testChecks.map((text, i) => <label key={text} className="flex cursor-pointer items-start gap-3 rounded-xl border p-4 leading-7"><input className="mt-2" type="checkbox" checked={a.testChoices[i]} onChange={e => update({ testChoices: a.testChoices.map((value, index) => index === i ? e.target.checked : value), testChecked: false })} />{text}</label>)}</div><label htmlFor="revisionPrompt" className="font-black">수정 지시</label><Textarea id="revisionPrompt" className="min-h-28 text-base md:text-base" maxLength={1000} value={a.revisionPrompt} onChange={e => update({ revisionPrompt: e.target.value, testChecked: false })} placeholder="예: 글자를 더 크게 하고, 준비물을 번호 목록으로 보여 줘." /><p className="text-sm text-muted-foreground">{a.revisionPrompt.trim().length} / 1000자 · 15자 이상</p><Button disabled={a.resultChoice === null || !a.testChoices.every(Boolean) || a.revisionPrompt.trim().length < 15} onClick={() => update({ testChecked: true })}>테스트와 수정 계획 확인</Button>{a.testChecked && <p role="status" className="rounded-xl bg-secondary p-4 leading-7">{a.resultChoice === 1 ? '테스트 계획을 확인했어요. 결과를 직접 써 보고, 불편한 점을 구체적으로 고치는 것이 중요해요.' : '결과가 보여도 꼭 직접 테스트해야 해요. 다시 선택해 보세요.'}</p>}</div>;
  return <div className="mt-6 space-y-6">{questions.map((q, i) => <fieldset key={q.title} className="rounded-2xl border p-4"><legend className="px-1 font-bold">퀴즈 {i + 1}</legend><p className="mb-3 font-bold leading-7">{q.title}</p><RadioCards name={`quiz-${i}`} options={q.options} value={a.answers[i]} onChange={answer => update({ answers: a.answers.map((value, index) => index === i ? answer : value), quizChecked: false })} />{a.quizChecked && <p className="mt-3 rounded-xl bg-secondary p-3 leading-7">{a.answers[i] === q.answer ? '정답이에요! ' : '다시 생각해 봐요. '}{q.tip}</p>}</fieldset>)}<Button disabled={a.answers.some(value => value === null)} onClick={() => update({ quizChecked: true })}>퀴즈 확인</Button>{a.quizChecked && <p role="status" className="font-bold">{questions.filter((q, i) => a.answers[i] === q.answer).length} / 3문항 정답</p>}<div><label htmlFor="reflection" className="font-black">오늘의 성찰</label><p className="my-2 leading-7">앱을 만들 때 내가 꼭 테스트하고 싶은 한 가지를 써 보세요.</p><Textarea id="reflection" className="min-h-28 text-base md:text-base" maxLength={1000} value={reflection} onChange={e => setReflection(e.target.value)} /><p className="mt-1 text-sm text-muted-foreground">{reflection.trim().length} / 1000자 · 10자 이상</p></div></div>;
}
