'use client';

import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { feedbackExamples, finalChecks, presentationIsReady, questions, shareOptions, type LessonTenActivities } from '@/lib/lesson-ten';

type Props = { step: number; activities: LessonTenActivities; update: (patch: Partial<LessonTenActivities>) => void; reflection: string; setReflection: (value: string) => void };

function Radios({ name, options, value, onChange }: { name: string; options: string[]; value: number | null; onChange: (value: number) => void }) {
  return <div className="space-y-3">{options.map((text, index) => <label key={text} className="flex cursor-pointer items-start gap-3 rounded-xl border p-4 leading-7"><input className="mt-2" type="radio" name={name} checked={value === index} onChange={() => onChange(index)} />{text}</label>)}</div>;
}

export function LessonTenContent({ step, activities: a, update, reflection, setReflection }: Props) {
  if (step === 1) return <div className="mt-6 space-y-6"><p className="leading-8">앱을 공유한다는 것은 내가 만든 생각과 사용 방법을 다른 사람에게 설명하고 의견을 듣는 일이에요. 실제 앱 파일을 올리지 않아도 준비된 발표 연습으로 안전하게 배울 수 있어요.</p><div className="rounded-2xl bg-orange-50 p-5 leading-7 text-orange-950"><p className="font-black">공유 전 약속</p><p className="mt-2">앱 화면과 설명에 나와 친구의 실제 이름, 연락처, 주소, 비밀번호가 없는지 먼저 확인해요.</p></div><fieldset><legend className="mb-3 font-black">안전한 앱 공유 방법은 무엇일까요?</legend><Radios name="share" options={shareOptions} value={a.shareChoice} onChange={shareChoice => update({ shareChoice, shareChecked: false })} /></fieldset><Button disabled={a.shareChoice === null} onClick={() => update({ shareChecked: true })}>공유 방법 확인</Button>{a.shareChecked && <output className="block rounded-xl bg-secondary p-4 leading-7">{a.shareChoice === 0 ? '정답이에요! 앱의 목표와 기능은 충분히 소개할 수 있어요.' : '공유 자료에는 나와 다른 사람의 개인정보를 넣지 않아요.'}</output>}</div>;

  if (step === 2) return <div className="mt-6 space-y-5"><p className="leading-7">친구가 앱의 목적과 사용 방법을 쉽게 이해하도록 짧은 발표 카드를 완성해 보세요.</p><div><label htmlFor="appName" className="font-black">앱 이름</label><Input id="appName" className="mt-2 text-base md:text-base" maxLength={80} value={a.appName} onChange={event => update({ appName: event.target.value, presentationChecked: false })} placeholder="예: 준비물 척척" /></div><div><label htmlFor="problemSummary" className="font-black">이 앱이 해결하는 문제</label><Textarea id="problemSummary" className="mt-2 min-h-24 text-base md:text-base" maxLength={600} value={a.problemSummary} onChange={event => update({ problemSummary: event.target.value, presentationChecked: false })} placeholder="누가 어떤 불편을 해결할 수 있는지 15자 이상으로 써 보세요." /></div><div><label htmlFor="featureSummary" className="font-black">핵심 기능 두 개와 연결 방법</label><Textarea id="featureSummary" className="mt-2 min-h-28 text-base md:text-base" maxLength={800} value={a.featureSummary} onChange={event => update({ featureSummary: event.target.value, presentationChecked: false })} placeholder="첫 기능의 결과가 다음 기능에 어떻게 쓰이는지 20자 이상으로 설명하세요." /></div><div><label htmlFor="demoSteps" className="font-black">친구에게 보여 줄 사용 순서</label><Textarea id="demoSteps" className="mt-2 min-h-28 text-base md:text-base" maxLength={800} value={a.demoSteps} onChange={event => update({ demoSteps: event.target.value, presentationChecked: false })} placeholder="1. 조건 선택 → 2. 결과 확인처럼 20자 이상으로 써 보세요." /></div><Button disabled={a.appName.trim().length < 2 || a.problemSummary.trim().length < 15 || a.featureSummary.trim().length < 20 || a.demoSteps.trim().length < 20} onClick={() => update({ presentationChecked: true })}>발표 카드 확인</Button>{a.presentationChecked && <output className="block rounded-xl bg-secondary p-4 leading-7">{presentationIsReady(a) ? '좋아요! 개인정보 없이 앱의 목표와 사용 흐름을 이해하기 쉽게 준비했어요.' : '개인정보처럼 보이는 내용을 빼고 일반적인 설명으로 바꿔 보세요.'}</output>}</div>;

  if (step === 3) return <div className="mt-6 space-y-6"><p className="leading-7">좋은 피드백은 사람을 평가하지 않고 앱의 구체적인 부분을 말해요. 각 문장이 앱을 개선하는 데 도움이 되는지 판단해 보세요.</p>{feedbackExamples.map((example, index) => <fieldset key={example.text} className="rounded-2xl border p-4"><legend className="px-1 font-black">피드백 {index + 1}</legend><p className="mb-3 leading-7">“{example.text}”</p><Radios name={`feedback-${index}`} options={['도움이 되기 어려운 피드백', '구체적이고 도움이 되는 피드백']} value={a.feedbackChoices[index]} onChange={answer => update({ feedbackChoices: a.feedbackChoices.map((value, answerIndex) => answerIndex === index ? answer : value), feedbackChecked: false })} /></fieldset>)}<Button disabled={a.feedbackChoices.some(value => value === null)} onClick={() => update({ feedbackChecked: true })}>피드백 판단 확인</Button>{a.feedbackChecked && <output className="block rounded-xl bg-secondary p-4 leading-7">{feedbackExamples.every((example, index) => a.feedbackChoices[index] === (example.good ? 1 : 0)) ? '정답이에요! 구체적인 위치와 바라는 변화가 있는 피드백을 찾았어요.' : '좋았던 점이나 불편한 위치, 원하는 변화를 구체적으로 말했는지 다시 살펴보세요.'}</output>}</div>;

  if (step === 4) return <div className="mt-6 space-y-6"><p className="leading-7">받은 의견 중 앱의 목표에 도움이 되는 것을 고르고, 수정한 뒤 다시 테스트할 계획을 세워 보세요.</p><div><label htmlFor="chosenFeedback" className="font-black">선택한 피드백</label><Textarea id="chosenFeedback" className="mt-2 min-h-24 text-base md:text-base" maxLength={800} value={a.chosenFeedback} onChange={event => update({ chosenFeedback: event.target.value, improvementChecked: false })} placeholder="어떤 피드백을 반영할지와 그 이유를 15자 이상으로 써 보세요." /></div><div><label htmlFor="improvementPlan" className="font-black">개선 전 → 개선 후 계획</label><Textarea id="improvementPlan" className="mt-2 min-h-32 text-base md:text-base" maxLength={1000} value={a.improvementPlan} onChange={event => update({ improvementPlan: event.target.value, improvementChecked: false })} placeholder="예: 다음 버튼이 작았어요 → 버튼을 크게 하고 ‘결과 보기’라고 바꾼 뒤 다시 눌러 볼 거예요." /><p className="mt-1 text-sm text-muted-foreground">{a.improvementPlan.trim().length} / 1000자 · 20자 이상</p></div><fieldset><legend className="mb-3 font-black">최종 점검표</legend><div className="space-y-3">{finalChecks.map((text, index) => <label key={text} className="flex cursor-pointer items-start gap-3 rounded-xl border p-4 leading-7"><input className="mt-2" type="checkbox" checked={a.finalChoices[index]} onChange={event => update({ finalChoices: a.finalChoices.map((value, choiceIndex) => choiceIndex === index ? event.target.checked : value), improvementChecked: false })} />{text}</label>)}</div></fieldset><Button disabled={a.chosenFeedback.trim().length < 15 || a.improvementPlan.trim().length < 20 || !a.finalChoices.every(Boolean)} onClick={() => update({ improvementChecked: true })}>개선 계획 확인</Button>{a.improvementChecked && <output className="block rounded-xl bg-secondary p-4 leading-7">좋아요! 피드백을 고른 이유와 수정·재테스트 방법까지 준비했어요.</output>}</div>;

  return <div className="mt-6 space-y-6"><div className="rounded-2xl border-2 border-primary/30 bg-primary/5 p-5"><p className="font-black text-primary">10차시 완주 점검</p><p className="mt-2 leading-7">문제 찾기 → 기능 설계 → 제작 지시 → 테스트 → 피드백 → 개선의 순서를 기억하며 퀴즈에 답해 보세요.</p></div>{questions.map((question, index) => <fieldset key={question.title} className="rounded-2xl border p-4"><legend className="px-1 font-bold">퀴즈 {index + 1}</legend><p className="mb-3 font-bold leading-7">{question.title}</p><Radios name={`quiz-${index}`} options={question.options} value={a.answers[index]} onChange={answer => update({ answers: a.answers.map((value, answerIndex) => answerIndex === index ? answer : value), quizChecked: false })} />{a.quizChecked && <p className="mt-3 rounded-xl bg-secondary p-3 leading-7">{a.answers[index] === question.answer ? '정답이에요! ' : '다시 생각해 봐요. '}{question.tip}</p>}</fieldset>)}<Button disabled={a.answers.some(value => value === null)} onClick={() => update({ quizChecked: true })}>퀴즈 확인</Button>{a.quizChecked && <output className="block font-bold">{questions.filter((question, index) => a.answers[index] === question.answer).length} / 3문항 정답</output>}<div><label htmlFor="reflection" className="font-black">10차시를 마친 성찰</label><p className="my-2 leading-7">AI 코딩으로 앱을 만들 때 앞으로 꼭 실천하고 싶은 것을 한 문장으로 써 보세요.</p><Textarea id="reflection" className="min-h-28 text-base md:text-base" maxLength={1000} value={reflection} onChange={event => setReflection(event.target.value)} /><p className="mt-1 text-sm text-muted-foreground">{reflection.trim().length} / 1000자 · 10자 이상</p></div></div>;
}
