'use client';
import { CanvaWorkflow, LessonSchedule } from '@/components/lesson-workflow';

import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { feedbackExamples, finalChecks, presentationIsReady, questions, shareOptions, type LessonTenActivities } from '@/lib/lesson-ten';

type Props = { step: number; activities: LessonTenActivities; update: (patch: Partial<LessonTenActivities>) => void; reflection: string; setReflection: (value: string) => void };

function Radios({ name, options, value, onChange }: { name: string; options: string[]; value: number | null; onChange: (value: number) => void }) {
  return <div className="space-y-3">{options.map((text, index) => <label key={text} className="flex cursor-pointer items-start gap-3 rounded-xl border p-4 leading-7"><input className="mt-2" type="radio" name={name} checked={value === index} onChange={() => onChange(index)} />{text}</label>)}</div>;
}

export function LessonTenContent({ step, activities: a, update, reflection, setReflection }: Props) {
  if (step === 1) return <div className="mt-6 space-y-6"><p className="leading-8">9차시의 자기 Canva 앱을 다시 열어 짝에게 소개하고 실제 의견으로 한 곳을 개선해요. 공유 URL은 발표·실행용이고 수정에는 원본 프로젝트/AI 코드 대화가 필요해요. 원본이 없거나 미완성이라면 마지막 작품을 보존하고 별도 보충으로 이어가요. 새 앱 생성 시간은 오늘 운영안에 포함하지 않아요.</p><LessonSchedule>도입·원본/계획 2 + 안전 공유 2 + 발표 카드 5 + 예시 판단 3 + Canva 이동·준비 2 + 동시 짝 발표·사용·의견 6 + 의견·개선 기록 3 + 수정·생성 대기 5 + 같은 순서 재시험·체크 3 + 퀴즈 3 + 성찰 2 + 저장·정리·여유 4 = 40분. 교사는 특정 화면의 의견을 짧게 시범 보여요. 28분에 수정 상태를 보고 31분에 외부 작업을 마무리해요. 미반영은 개선했다고 체크하지 않아요.</LessonSchedule><div className="rounded-2xl bg-orange-50 p-5 leading-7 text-orange-950"><p className="font-black">공유 전 약속</p><p className="mt-2">앱 화면과 설명에 나와 친구의 실제 이름, 연락처, 주소, 비밀번호가 없는지 먼저 확인해요.</p></div><fieldset><legend className="mb-3 font-black">안전한 앱 공유 방법은 무엇일까요?</legend><Radios name="share" options={shareOptions} value={a.shareChoice} onChange={shareChoice => update({ shareChoice, shareChecked: false })} /></fieldset><Button disabled={a.shareChoice === null} onClick={() => update({ shareChecked: true })}>공유 방법 확인</Button>{a.shareChecked && <output className="block rounded-xl bg-secondary p-4 leading-7">{a.shareChoice === 0 ? '정답이에요! 앱의 목표와 기능은 충분히 소개할 수 있어요.' : '공유 자료에는 나와 다른 사람의 개인정보를 넣지 않아요.'}</output>}</div>;

  if (step === 2) return <div className="mt-6 space-y-5"><p className="leading-7">원본 Canva AI 코드 대화나 이미 보관한 계획의 이름·문제·두 기능 문장을 수동으로 옮기고 사용 순서만 덧붙여요. 기존 글은 필요한 부분만 고쳐요. 틀: 누구의 __문제 / 기능1 __ → 그 결과로 기능2 __ / 친구가 누를 순서 __.</p><div><label htmlFor="appName" className="font-black">앱 이름</label><Input id="appName" className="mt-2 text-base md:text-base" maxLength={80} value={a.appName} onChange={event => update({ appName: event.target.value, presentationChecked: false })} placeholder="예: 준비물 척척" /></div><div><label htmlFor="problemSummary" className="font-black">이 앱이 해결하는 문제</label><Textarea id="problemSummary" className="mt-2 min-h-24 text-base md:text-base" maxLength={600} value={a.problemSummary} onChange={event => update({ problemSummary: event.target.value, presentationChecked: false })} placeholder="누가 어떤 불편을 해결할 수 있는지 15자 이상으로 써 보세요." /></div><div><label htmlFor="featureSummary" className="font-black">핵심 기능 두 개와 연결 방법</label><Textarea id="featureSummary" className="mt-2 min-h-28 text-base md:text-base" maxLength={800} value={a.featureSummary} onChange={event => update({ featureSummary: event.target.value, presentationChecked: false })} placeholder="첫 기능의 결과가 다음 기능에 어떻게 쓰이는지 20자 이상으로 설명하세요." /></div><div><label htmlFor="demoSteps" className="font-black">친구에게 보여 줄 사용 순서</label><Textarea id="demoSteps" className="mt-2 min-h-28 text-base md:text-base" maxLength={800} value={a.demoSteps} onChange={event => update({ demoSteps: event.target.value, presentationChecked: false })} placeholder="1. 조건 선택 → 2. 결과 확인처럼 20자 이상으로 써 보세요." /></div><Button disabled={a.appName.trim().length < 2 || a.problemSummary.trim().length < 15 || a.featureSummary.trim().length < 20 || a.demoSteps.trim().length < 20} onClick={() => update({ presentationChecked: true })}>발표 카드 확인</Button>{a.presentationChecked && <output className="block rounded-xl bg-secondary p-4 leading-7">{presentationIsReady(a) ? '글 길이와 일부 개인정보 형태를 확인했어요. 목적·두 기능·사용 순서가 실제 앱과 맞는지는 직접 읽고 짝에게 확인해요.' : '개인정보 형태나 요구로 보이는 내용을 고쳐요. 실제 값은 빼고 “비밀번호를 요구하지 않는다” 같은 안전 조건을 써요. 자동 확인이 모든 뜻을 이해하는 것은 아니에요.'}</output>}</div>;

  if (step === 3) return <div className="mt-6 space-y-6"><p className="leading-7">아래 세 문장은 분류 연습용 예시예요. 실제 짝에게 받은 말과 구별해요. 좋은 피드백은 앱의 특정 화면·좋았던 점이나 어려움·바라는 변화를 말해요. 사람을 평가하지 않아요.</p>{feedbackExamples.map((example, index) => <fieldset key={example.text} className="rounded-2xl border p-4"><legend className="px-1 font-black">피드백 {index + 1}</legend><p className="mb-3 leading-7">“{example.text}”</p><Radios name={`feedback-${index}`} options={['도움이 되기 어려운 피드백', '구체적이고 도움이 되는 피드백']} value={a.feedbackChoices[index]} onChange={answer => update({ feedbackChoices: a.feedbackChoices.map((value, answerIndex) => answerIndex === index ? answer : value), feedbackChecked: false })} /></fieldset>)}<Button disabled={a.feedbackChoices.some(value => value === null)} onClick={() => update({ feedbackChecked: true })}>피드백 판단 확인</Button>{a.feedbackChecked && <output className="block rounded-xl bg-secondary p-4 leading-7">{feedbackExamples.every((example, index) => a.feedbackChoices[index] === (example.good ? 1 : 0)) ? '정답이에요! 구체적인 위치와 바라는 변화가 있는 피드백을 찾았어요.' : '좋았던 점이나 불편한 위치, 원하는 변화를 구체적으로 말했는지 다시 살펴보세요.'}</output>}<CanvaWorkflow><ol className="mt-3 list-decimal space-y-2 pl-5"><li>앱을 열고 짝끼리 동시에 발표해요. 한 사람당 1분 소개 + 1분 상대 사용 + 1분 구체적 의견을 주고 교대해요.</li><li>짝은 앱 화면의 한 곳을 근거로 의견을 말해요. 개인정보는 공유하지 않아요.</li><li>웹 4단계에 실제 의견과 선택 이유를 적어요. 빠른 학생은 반영하지 않을 의견의 이유도 설명해요.</li></ol></CanvaWorkflow></div>;

  if (step === 4) return <div className="mt-6 space-y-6"><p className="leading-7">짝 발표에서 실제로 받은 의견 한 가지와 고른 이유를 적어요. 웹 예시를 내 짝의 말로 쓰지 않아요. 개선 계획을 Canva 원본에서 실행한 뒤 같은 순서로 재시험하고 돌아와요. 지원이 필요하면 버튼 이름·안내 한 줄처럼 작은 개선을 골라요.</p><div><label htmlFor="chosenFeedback" className="font-black">선택한 피드백</label><Textarea id="chosenFeedback" className="mt-2 min-h-24 text-base md:text-base" maxLength={800} value={a.chosenFeedback} onChange={event => update({ chosenFeedback: event.target.value, improvementChecked: false })} placeholder="실제 짝 의견: __화면에서 __가 어려웠어요. 목표 __에 도움이 되어 골랐어요. 15자 이상." /></div><div><label htmlFor="improvementPlan" className="font-black">개선 전 → 개선 후 계획</label><Textarea id="improvementPlan" className="mt-2 min-h-32 text-base md:text-base" maxLength={1000} value={a.improvementPlan} onChange={event => update({ improvementPlan: event.target.value, improvementChecked: false })} placeholder="개선 전 __ → Canva 수정 지시 __ → 같은 순서 재시험의 실제 결과 __ / 아직 반영 못 한 일 __. 20자 이상." /><p className="mt-1 text-sm text-muted-foreground">{a.improvementPlan.trim().length} / 1000자 · 20자 이상</p></div><CanvaWorkflow><ol className="mt-3 list-decimal space-y-2 pl-5"><li>선정한 한 곳의 개선 계획을 원본 Canva에 수정 지시로 옮겨요.</li><li>같은 조건·순서로 두 기능을 재시험하고 짝에게 안내가 쉬워졌는지 물어요.</li><li>웹으로 돌아와 개선 계획에 실제 전후 결과를 덧붙여요. 아래 네 조건을 실제로 충족한 때만 체크해요. 미수정·실패·미시험은 미체크로 저장해요.</li></ol></CanvaWorkflow><fieldset><legend className="mb-3 font-black">최종 점검표</legend><div className="space-y-3">{finalChecks.map((text, index) => <label key={text} className="flex cursor-pointer items-start gap-3 rounded-xl border p-4 leading-7"><input className="mt-2" type="checkbox" checked={a.finalChoices[index]} onChange={event => update({ finalChoices: a.finalChoices.map((value, choiceIndex) => choiceIndex === index ? event.target.checked : value), improvementChecked: false })} />{text}</label>)}</div></fieldset><Button disabled={a.chosenFeedback.trim().length < 15 || a.improvementPlan.trim().length < 20 || !a.finalChoices.every(Boolean)} onClick={() => update({ improvementChecked: true })}>개선 계획 확인</Button>{a.improvementChecked && <output className="block rounded-xl bg-secondary p-4 leading-7">글 길이와 내 최종 체크를 확인했어요. 실제 의견·수정·재시험 기록이 맞는지 다시 읽어요. 웹이 Canva 개선을 자동 검증한 것은 아니에요.</output>}</div>;

  return <div className="mt-6 space-y-6"><div className="rounded-2xl border-2 border-primary/30 bg-primary/5 p-5"><p className="font-black text-primary">10차시 활동 점검</p><p className="mt-2 leading-7">문제 찾기 → 기능 설계 → 제작 지시 → 테스트 → 피드백 → 개선의 순서를 기억하며 퀴즈에 답해 보세요.</p></div>{questions.map((question, index) => <fieldset key={question.title} className="rounded-2xl border p-4"><legend className="px-1 font-bold">퀴즈 {index + 1}</legend><p className="mb-3 font-bold leading-7">{question.title}</p><Radios name={`quiz-${index}`} options={question.options} value={a.answers[index]} onChange={answer => update({ answers: a.answers.map((value, answerIndex) => answerIndex === index ? answer : value), quizChecked: false })} />{a.quizChecked && <p className="mt-3 rounded-xl bg-secondary p-3 leading-7">{a.answers[index] === question.answer ? '정답이에요! ' : '다시 생각해 봐요. '}{question.tip}</p>}</fieldset>)}<Button disabled={a.answers.some(value => value === null)} onClick={() => update({ quizChecked: true })}>퀴즈 확인</Button>{a.quizChecked && <output className="block font-bold">{questions.filter((question, index) => a.answers[index] === question.answer).length} / 3문항 정답</output>}<div><label htmlFor="reflection" className="font-black">10차시를 마친 성찰</label><p className="my-2 leading-7">실제 짝 의견 __ / 개선 전 __ → 개선 뒤 관찰 __ / 아직 못 한 일 __. 앞으로 __를 실천할 거예요. 이 완료는 10차시 활동 기록이며 다른 차시 완료는 수업 홈에서 확인해요.</p><Textarea id="reflection" className="min-h-28 text-base md:text-base" maxLength={1000} value={reflection} onChange={event => setReflection(event.target.value)} /><p className="mt-1 text-sm text-muted-foreground">{reflection.trim().length} / 1000자 · 10자 이상</p></div></div>;
}
