'use client';

import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { questions, safetyItems, strengthItems, limitationItems, type LessonThreeActivities } from '@/lib/lesson-three';

type Props = { step: number; activities: LessonThreeActivities; update: (patch: Partial<LessonThreeActivities>) => void; reflection: string; setReflection: (value: string) => void };
function ChoiceList({ items, values, checked, name, onChange, options = ['AI가 도움을 줄 수 있어요', 'AI만으로 판단하기 어려워요'] }: { items: typeof strengthItems; values: Array<number | null>; checked: boolean; name: string; options?: string[]; onChange: (values: Array<number | null>) => void }) {
  return <div className="space-y-4">{items.map((item, i) => <fieldset key={item.text} className="rounded-2xl border p-4"><legend className="px-1 font-bold">사례 {i + 1}</legend><p className="mb-3 leading-7">{item.text}</p><div className="flex flex-wrap gap-3">{options.map((label, j) => <label key={label} className="flex cursor-pointer items-center gap-2 rounded-xl border px-3 py-3 leading-6"><input type="radio" name={`${name}-${i}`} checked={values[i] === j} onChange={() => onChange(values.map((v, k) => k === i ? j : v))} />{label}</label>)}</div>{checked && <output className="block mt-3 rounded-xl bg-secondary p-3 leading-7">{values[i] === item.answer ? '정답이에요! ' : '다시 살펴봐요. '}{item.tip}</output>}</fieldset>)}</div>;
}
export function LessonThreeContent({ step, activities: a, update, reflection, setReflection }: Props) {
  if (step === 1) return <div className="mt-6 space-y-6"><p className="leading-8">AI는 여러 일을 빠르게 도와줄 수 있지만, 모든 일을 사람처럼 잘하는 것은 아니에요. 사례를 살펴보기 전에 지금의 생각을 골라 보세요.</p><details className="rounded-xl border p-4"><summary className="cursor-pointer font-bold">오늘의 40분 수업 흐름</summary><p className="mt-3 leading-7">접속·목표 3분 + 첫 생각 2분 + 강점 4분 + 한계 5분 + 안전 선택 6분 + 급식표 짝 비교 10분 + 퀴즈·성찰 6분 + 저장·정리 2분 + 여유 2분 = 40분</p><p className="mt-2 leading-7">교사의 예상 시간이에요. 비교가 어렵다면 날짜와 메뉴를 한 가지씩 짚고, 필수 답을 확인할 시간을 남겨요. 빠르게 마쳤다면 날짜가 다른 자료도 비교해 보세요.</p></details><fieldset className="space-y-3"><legend className="mb-3 font-bold">AI의 답은 언제나 맞을까요?</legend>{['언제나 맞아요.', '도움은 되지만 사람이 확인해야 해요.', '잘 모르겠어요. 사례를 살펴볼래요.'].map((s, i) => <label key={s} className="flex cursor-pointer items-start gap-3 rounded-xl border p-4 leading-7"><input className="mt-2" type="radio" name="opening" checked={a.opening === i} onChange={() => update({ opening: i })} />{s}</label>)}</fieldset>{a.opening !== null && <p className="rounded-xl bg-secondary p-4 leading-7">좋아요. 이제 AI가 잘하는 일과 어려워하는 일을 나누고, 사람이 확인해야 하는 이유를 알아봐요.</p>}</div>;
  if (step === 2) return <div className="mt-6 space-y-5"><p className="leading-7">AI가 도움을 줄 수 있는 사례를 골라 보세요. AI는 많은 예시에서 패턴을 찾거나 내용을 정리하고 아이디어를 제안하는 데 도움을 줄 수 있어요. 패턴은 여러 예에서 되풀이되는 특징이에요. 예를 들어 동물 사진에서 귀 모양이 비슷한 것을 찾을 수 있어요.</p><p className="leading-7">한 사례를 골라 짝에게 “AI는 ___을 도와주지만, 사람은 ___을 확인해야 해”라고 말해 보세요.</p><ChoiceList items={strengthItems} values={a.strengthChoices} checked={a.strengthChecked} name="strength" onChange={strengthChoices => update({ strengthChoices, strengthChecked: false })} /><Button disabled={a.strengthChoices.some(v => v === null)} onClick={() => update({ strengthChecked: true })}>분류 결과 확인</Button>{a.strengthChecked && <output className="block font-bold">{strengthItems.filter((x, i) => a.strengthChoices[i] === x.answer).length} / {strengthItems.length}개 정답</output>}</div>;
  if (step === 3) return <div className="mt-6 space-y-5"><p className="leading-7">이번에는 AI만으로 판단하기 어려운 사례를 골라 보세요. AI가 그럴듯하게 말해도 최신 정보·감정·맥락은 사람이 다시 확인해야 해요. 맥락은 앞뒤 상황이에요. 친구의 표정 하나만 보고 마음을 단정하지 말고 무슨 일이 있었는지 물어봐요.</p><ChoiceList items={limitationItems} values={a.limitationChoices} checked={a.limitationChecked} name="limitation" onChange={limitationChoices => update({ limitationChoices, limitationChecked: false })} /><Button disabled={a.limitationChoices.some(v => v === null)} onClick={() => update({ limitationChecked: true })}>분류 결과 확인</Button>{a.limitationChecked && <output className="block font-bold">{limitationItems.filter((x, i) => a.limitationChoices[i] === x.answer).length} / {limitationItems.length}개 정답</output>}</div>;
  if (step === 4) return <div className="mt-6 space-y-5"><p className="leading-7">이 행동은 안전한가요? 사실을 확인하고 개인정보를 지키는 행동인지 판단해 보세요.</p><ChoiceList items={safetyItems} values={a.verificationChoices} checked={a.verificationChecked} name="safety" options={['안전한 확인 방법이에요', '개인정보나 틀린 정보 위험이 있어요']} onChange={verificationChoices => update({ verificationChoices, verificationChecked: false })} /><Button disabled={a.verificationChoices.some(v => v === null)} onClick={() => update({ verificationChecked: true })}>안전한 선택 확인</Button>{a.verificationChecked && <output className="block font-bold">{safetyItems.filter((x, i) => a.verificationChoices[i] === x.answer).length} / {safetyItems.length}개 정답</output>}<MealComparison /></div>;
  return <div className="mt-6 space-y-6">{questions.map((q, i) => <fieldset key={q.title} className="rounded-2xl border p-4"><legend className="px-1 font-bold">퀴즈 {i + 1}</legend><p className="mb-3 font-bold leading-7">{q.title}</p><div className="space-y-3">{q.options.map((s, j) => <label key={s} className="flex cursor-pointer items-start gap-3 rounded-lg bg-muted/60 p-3 leading-7"><input className="mt-2" type="radio" name={`quiz-${i}`} checked={a.answers[i] === j} onChange={() => update({ answers: a.answers.map((v, k) => k === i ? j : v), quizChecked: false })} />{s}</label>)}</div>{a.quizChecked && <output className="block mt-3 rounded-xl bg-secondary p-3 leading-7">{a.answers[i] === q.answer ? '정답이에요! ' : '다시 생각해 봐요. '}{q.tip}</output>}</fieldset>)}<Button disabled={a.answers.some(v => v === null)} onClick={() => update({ quizChecked: true })}>퀴즈 확인</Button>{a.quizChecked && <output className="block font-bold">{questions.filter((q, i) => a.answers[i] === q.answer).length} / 3문항 정답</output>}<div><label htmlFor="reflection" className="font-black">오늘의 성찰</label><p className="my-2 leading-7">급식표 비교에서 찾은 근거와 고칠 내용을 써 보세요. 다른 사례를 쓴다면 어떤 자료로 무엇을 확인할지도 적어요.</p><p className="my-2 rounded-xl bg-secondary p-3 leading-7">문장 틀: “AI는 ___라고 했지만, 같은 날짜 급식표에는 ___이므로 ___로 고친다.” 틀을 그대로 복사하지 말고 내가 비교한 내용을 넣어요.</p><Textarea id="reflection" className="min-h-32 text-base md:text-base" maxLength={1000} value={reflection} onChange={e => setReflection(e.target.value)} /><p className="mt-1 text-sm text-muted-foreground">{reflection.trim().length} / 1000자 · 10자 이상</p></div></div>;
}

function MealComparison() {
  return <section className="space-y-4 rounded-2xl border-2 border-primary/30 p-5" aria-labelledby="meal-comparison">
    <h3 id="meal-comparison" className="text-xl font-black">급식 정보 탐정 · 짝과 비교하기</h3>
    <p className="leading-7">아래는 수업용 가상 자료예요. 실제 학교의 급식 안내가 아니에요. 근거는 답을 확인할 때 사용하는 자료예요.</p>
    <div className="grid gap-4 sm:grid-cols-2">
      <div className="rounded-xl bg-muted p-4"><h4 className="font-bold">가상의 AI 답</h4><p className="mt-2 leading-7">10월 7일 급식은 보리밥, 미역국, 닭볶음, 배추김치, 사과예요.</p></div>
      <div className="rounded-xl bg-secondary p-4"><h4 className="font-bold">가상의 학교 급식표</h4><p className="mt-2 leading-7">학교가 안내한 이번 주 급식표<br />10월 7일: 보리밥, 미역국, 닭볶음, 배추김치, 배</p></div>
    </div>
    <ol className="list-decimal space-y-2 pl-5 leading-7"><li>두 자료의 날짜가 같은지 확인해요.</li><li>서로 다른 메뉴 한 가지를 찾아요. 짝에게 자료 속 단어를 짚어 설명해요.</li><li>“AI 답의 ___을 ___로 고쳐야 해”라고 말해요. 다음 단계 성찰에 근거를 남겨요.</li></ol>
    <details className="rounded-xl border p-4"><summary className="cursor-pointer font-bold">먼저 비교한 뒤 설명 보기</summary><p className="mt-3 leading-7">날짜는 모두 10월 7일이에요. AI 답은 사과, 학교 급식표는 배라고 했어요. 같은 날짜의 학교 안내를 근거로 사과를 배로 고쳐요. AI가 자신 있게 말한 것만으로 맞는 정보가 되지는 않아요.</p></details>
    <p className="leading-7">더 해보기: 다른 자료에 “10월 6일 · 사과”라고 쓰여 있다면 10월 7일 답의 근거로 써도 될까요? 짝과 이유를 말해 보세요.</p>
  </section>;
}
