'use client';

import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { questions, safetyItems, strengthItems, limitationItems, type LessonThreeActivities } from '@/lib/lesson-three';

type Props = { step: number; activities: LessonThreeActivities; update: (patch: Partial<LessonThreeActivities>) => void; reflection: string; setReflection: (value: string) => void };
function ChoiceList({ items, values, checked, name, onChange }: { items: typeof strengthItems; values: Array<number | null>; checked: boolean; name: string; onChange: (values: Array<number | null>) => void }) {
  return <div className="space-y-4">{items.map((item, i) => <fieldset key={item.text} className="rounded-2xl border p-4"><legend className="px-1 font-bold">사례 {i + 1}</legend><p className="mb-3 leading-7">{item.text}</p><div className="flex flex-wrap gap-3">{['AI가 도움을 줄 수 있어요', 'AI만으로 판단하기 어려워요'].map((label, j) => <label key={label} className="flex cursor-pointer items-center gap-2 rounded-xl border px-3 py-3 leading-6"><input type="radio" name={`${name}-${i}`} checked={values[i] === j} onChange={() => onChange(values.map((v, k) => k === i ? j : v))} />{label}</label>)}</div>{checked && <p className="mt-3 rounded-xl bg-secondary p-3 leading-7">{values[i] === item.answer ? '정답이에요! ' : '다시 살펴봐요. '}{item.tip}</p>}</fieldset>)}</div>;
}
export function LessonThreeContent({ step, activities: a, update, reflection, setReflection }: Props) {
  if (step === 1) return <div className="mt-6 space-y-6"><p className="leading-8">AI는 여러 일을 빠르게 도와줄 수 있지만, 모든 일을 사람처럼 잘하는 것은 아니에요. 사례를 살펴보기 전에 지금의 생각을 골라 보세요.</p><fieldset className="space-y-3"><legend className="mb-3 font-bold">AI의 답은 언제나 맞을까요?</legend>{['언제나 맞아요.', '도움은 되지만 사람이 확인해야 해요.', '잘 모르겠어요. 사례를 살펴볼래요.'].map((s, i) => <label key={s} className="flex cursor-pointer items-start gap-3 rounded-xl border p-4 leading-7"><input className="mt-2" type="radio" name="opening" checked={a.opening === i} onChange={() => update({ opening: i })} />{s}</label>)}</fieldset>{a.opening !== null && <p className="rounded-xl bg-secondary p-4 leading-7">좋아요. 이제 AI가 잘하는 일과 어려워하는 일을 나누고, 사람이 확인해야 하는 이유를 알아봐요.</p>}</div>;
  if (step === 2) return <div className="mt-6 space-y-5"><p className="leading-7">AI가 도움을 줄 수 있는 사례를 골라 보세요. AI는 많은 예시에서 패턴을 찾거나 내용을 정리하고 아이디어를 제안하는 데 도움을 줄 수 있어요.</p><ChoiceList items={strengthItems} values={a.strengthChoices} checked={a.strengthChecked} name="strength" onChange={strengthChoices => update({ strengthChoices, strengthChecked: false })} /><Button disabled={a.strengthChoices.some(v => v === null)} onClick={() => update({ strengthChecked: true })}>분류 결과 확인</Button>{a.strengthChecked && <p role="status" className="font-bold">{strengthItems.filter((x, i) => a.strengthChoices[i] === x.answer).length} / {strengthItems.length}개 정답</p>}</div>;
  if (step === 3) return <div className="mt-6 space-y-5"><p className="leading-7">이번에는 AI만으로 판단하기 어려운 사례를 골라 보세요. AI가 그럴듯하게 말해도 최신 정보·감정·맥락은 사람이 다시 확인해야 해요.</p><ChoiceList items={limitationItems} values={a.limitationChoices} checked={a.limitationChecked} name="limitation" onChange={limitationChoices => update({ limitationChoices, limitationChecked: false })} /><Button disabled={a.limitationChoices.some(v => v === null)} onClick={() => update({ limitationChecked: true })}>분류 결과 확인</Button>{a.limitationChecked && <p role="status" className="font-bold">{limitationItems.filter((x, i) => a.limitationChoices[i] === x.answer).length} / {limitationItems.length}개 정답</p>}</div>;
  if (step === 4) return <div className="mt-6 space-y-5"><p className="leading-7">사실을 확인하거나 개인정보를 지키는 방법을 골라 보세요.</p><ChoiceList items={safetyItems} values={a.verificationChoices} checked={a.verificationChecked} name="safety" onChange={verificationChoices => update({ verificationChoices, verificationChecked: false })} /><Button disabled={a.verificationChoices.some(v => v === null)} onClick={() => update({ verificationChecked: true })}>안전한 선택 확인</Button>{a.verificationChecked && <p role="status" className="font-bold">{safetyItems.filter((x, i) => a.verificationChoices[i] === x.answer).length} / {safetyItems.length}개 정답</p>}</div>;
  return <div className="mt-6 space-y-6">{questions.map((q, i) => <fieldset key={q.title} className="rounded-2xl border p-4"><legend className="px-1 font-bold">퀴즈 {i + 1}</legend><p className="mb-3 font-bold leading-7">{q.title}</p><div className="space-y-3">{q.options.map((s, j) => <label key={s} className="flex cursor-pointer items-start gap-3 rounded-lg bg-muted/60 p-3 leading-7"><input className="mt-2" type="radio" name={`quiz-${i}`} checked={a.answers[i] === j} onChange={() => update({ answers: a.answers.map((v, k) => k === i ? j : v), quizChecked: false })} />{s}</label>)}</div>{a.quizChecked && <p className="mt-3 rounded-xl bg-secondary p-3 leading-7">{a.answers[i] === q.answer ? '정답이에요! ' : '다시 생각해 봐요. '}{q.tip}</p>}</fieldset>)}<Button disabled={a.answers.some(v => v === null)} onClick={() => update({ quizChecked: true })}>퀴즈 확인</Button>{a.quizChecked && <p role="status" className="font-bold">{questions.filter((q, i) => a.answers[i] === q.answer).length} / 3문항 정답</p>}<div><label htmlFor="reflection" className="font-black">오늘의 성찰</label><p className="my-2 leading-7">AI의 답을 받은 뒤 내가 해야 할 일을 한 가지 이상 써 보세요.</p><Textarea id="reflection" className="min-h-32 text-base md:text-base" maxLength={1000} value={reflection} onChange={e => setReflection(e.target.value)} /><p className="mt-1 text-sm text-muted-foreground">{reflection.trim().length} / 1000자 · 10자 이상</p></div></div>;
}
