'use client';

import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { clueItems, detailOptions, questions, revisionItems, lessonFourExamples, playBaseRequest, type LessonFourActivities } from '@/lib/lesson-four';

type Props = { step: number; activities: LessonFourActivities; update: (patch: Partial<LessonFourActivities>) => void; reflection: string; setReflection: (value: string) => void };

export function LessonFourContent({ step, activities: a, update, reflection, setReflection }: Props) {
  if (step === 1) return <div className="mt-6 space-y-6"><p className="leading-8">AI에게 부탁할 때는 짧기만 한 말보다, 내가 원하는 것을 알아듣기 쉽게 알려 주는 말이 좋아요. 두 요청 중 더 이해하기 쉬운 것을 골라 보세요.</p><details className="rounded-xl border p-4"><summary className="cursor-pointer font-bold">오늘의 40분 수업 흐름</summary><p className="mt-3 leading-7">도입·요청 비교 4분 + 단서 예시·분류 6분 + 놀이 두 결과 비교 8분 + 수정 요청·짝 확인 6분 + 퀴즈 5분 + 나만의 지시·성찰 7분 + 저장·정리·여유 4분 = 40분</p><p className="mt-2 leading-7">교사의 예상 시간이에요. 두 단서의 예를 먼저 함께 읽고, 네 문항 모두 선택·확인해요. 시간이 부족하면 추가 조건 실험을 생략하고 필수 글·퀴즈·저장을 마쳐요.</p></details><fieldset className="space-y-3"><legend className="mb-3 font-bold">쉬는 시간 놀이를 부탁한다면?</legend>{['놀이를 재미있게 추천해 줘.', '6학년이 쉬는 시간 10분 동안 준비물 없이 할 놀이를 3가지, 이름과 방법을 표로 추천해 줘.'].map((s, i) => <label key={s} className="flex cursor-pointer items-start gap-3 rounded-xl border p-4 leading-7"><input className="mt-2" type="radio" name="opening" checked={a.opening === i} onChange={() => update({ opening: i })} />{s}</label>)}</fieldset>{a.opening !== null && <output className="block rounded-xl bg-secondary p-4 leading-7">{a.opening === 1 ? '맞아요. 대상·시간·준비물·개수·결과 모양을 알려 주면 원하는 답인지 비교할 수 있어요.' : '“재미있게”만으로는 누가 할 놀이인지, 몇 가지인지 알기 어려워요. 대상·개수·결과 모양이 있는 요청을 다시 골라 보세요.'}</output>}</div>;
  if (step === 2) return <div className="mt-6 space-y-5"><p className="leading-7">좋은 지시에는 네 가지 단서가 있어요. 각 문장이 어떤 단서인지 골라 보세요.</p><div className="space-y-4">{clueItems.map((item, i) => <fieldset key={item.text} className="rounded-2xl border p-4"><legend className="px-1 font-bold">단서 {i + 1}</legend><p className="mb-3 leading-7">{item.text}</p><div className="flex flex-wrap gap-2">{['목표', '상황', '조건', '결과 형식'].map((label, j) => <label key={label} className="flex cursor-pointer items-center gap-2 rounded-xl border px-3 py-3"><input type="radio" name={`clue-${i}`} checked={a.clueChoices[i] === j} onChange={() => update({ clueChoices: a.clueChoices.map((v, k) => k === i ? j : v), cluesChecked: false })} />{label}</label>)}</div>{a.cluesChecked && <p className="mt-3 rounded-xl bg-secondary p-3">{a.clueChoices[i] === item.answer ? '정답이에요! ' : `이 문장은 ‘${item.label}’ 단서예요. `}{item.tip}</p>}</fieldset>)}</div><Button disabled={a.clueChoices.some(v => v === null)} onClick={() => update({ cluesChecked: true })}>단서 확인</Button>{a.cluesChecked && <output className="block font-bold">{clueItems.filter((x, i) => a.clueChoices[i] === x.answer).length} / 4개 정답</output>}</div>;
  if (step === 3) return <div className="mt-6 space-y-5"><p className="leading-7">{playBaseRequest} 여기에 더할 조건을 두 가지 이상 골라요. 선택한 조건에 따라 예시 B가 달라져요.</p><div className="space-y-3">{detailOptions.map((s, i) => <label key={s} className="flex cursor-pointer items-center gap-3 rounded-xl border p-4 leading-7"><input type="checkbox" checked={a.detailChoices[i]} onChange={e => update({ detailChoices: a.detailChoices.map((v, k) => k === i ? e.target.checked : v), detailResultChecked: false })} />{s}</label>)}</div><Button disabled={a.detailChoices.filter(Boolean).length < 2} onClick={() => update({ detailResultChecked: true })}>두 예시 결과 비교하기</Button>{a.detailResultChecked && <PlayComparison choices={a.detailChoices} />}</div>;
  if (step === 4) return <div className="mt-6 space-y-5"><p className="leading-7">첫 결과가 부족하면 무엇이 부족한지 구체적으로 말하고 다시 요청해요. 상황에 알맞은 수정 요청을 골라 보세요.</p><p className="rounded-xl bg-secondary p-4 leading-7">짝에게 앞의 예시 A에서 빠진 조건 하나를 말하고, “___이 부족해. ___로 바꿔 줘”라고 다시 요청해 보세요. 짝은 어떤 부분을 확인할지 말해요. 마지막 성찰에 이 근거를 남겨요.</p><div className="space-y-4">{revisionItems.map((item, i) => <fieldset key={item.text} className="rounded-2xl border p-4"><legend className="px-1 font-bold">상황 {i + 1}</legend><p className="mb-3 leading-7">{item.text}</p><div className="space-y-2">{item.options.map((s, j) => <label key={s} className="flex cursor-pointer items-start gap-3 rounded-xl bg-muted/60 p-3 leading-7"><input className="mt-2" type="radio" name={`revision-${i}`} checked={a.revisionChoices[i] === j} onChange={() => update({ revisionChoices: a.revisionChoices.map((v, k) => k === i ? j : v), revisionsChecked: false })} />{s}</label>)}</div>{a.revisionsChecked && <p className="mt-3 rounded-xl bg-secondary p-3">{a.revisionChoices[i] === item.answer ? '정답이에요! ' : '부족한 점을 더 구체적으로 말해 보세요. '}{item.tip}</p>}</fieldset>)}</div><Button disabled={a.revisionChoices.some(v => v === null)} onClick={() => update({ revisionsChecked: true })}>수정 요청 확인</Button>{a.revisionsChecked && <output className="block font-bold">{revisionItems.filter((x, i) => a.revisionChoices[i] === x.answer).length} / 3개 정답</output>}</div>;
  return <div className="mt-6 space-y-6">{questions.map((q, i) => <fieldset key={q.title} className="rounded-2xl border p-4"><legend className="px-1 font-bold">퀴즈 {i + 1}</legend><p className="mb-3 font-bold leading-7">{q.title}</p><div className="space-y-3">{q.options.map((s, j) => <label key={s} className="flex cursor-pointer items-start gap-3 rounded-lg bg-muted/60 p-3 leading-7"><input className="mt-2" type="radio" name={`quiz-${i}`} checked={a.answers[i] === j} onChange={() => update({ answers: a.answers.map((v, k) => k === i ? j : v), quizChecked: false })} />{s}</label>)}</div>{a.quizChecked && <p className="mt-3 rounded-xl bg-secondary p-3 leading-7">{a.answers[i] === q.answer ? '정답이에요! ' : '다시 생각해 봐요. '}{q.tip}</p>}</fieldset>)}<Button disabled={a.answers.some(v => v === null)} onClick={() => update({ quizChecked: true })}>퀴즈 확인</Button>{a.quizChecked && <output className="block font-bold">{questions.filter((q, i) => a.answers[i] === q.answer).length} / 3문항 정답</output>}<div><label htmlFor="ownPrompt" className="font-black">나만의 안전한 지시</label><p className="my-2 leading-7">개인정보 없이, 목표·상황·조건·결과 형식 중 두 가지 이상을 넣어 AI에게 부탁하는 문장을 써 보세요. 길이만으로 좋은 지시가 되는 것은 아니에요. 내가 넣은 단서 두 가지를 짝에게 짚어 설명해요.</p><p className="my-2 rounded-xl bg-secondary p-3 leading-7">문장 틀: “6학년을 위한 ___(을/를) ___개, ___ 조건에 맞춰 ___ 형식으로 제안해 줘.” 빈칸을 내 생각으로 채워요.</p><Textarea id="ownPrompt" className="min-h-32 text-base md:text-base" maxLength={1000} value={a.ownPrompt} onChange={e => update({ ownPrompt: e.target.value })} /><p className="mt-1 text-sm text-muted-foreground">{a.ownPrompt.trim().length} / 1000자 · 20자 이상</p></div><div><label htmlFor="reflection" className="font-black">오늘의 성찰</label><p className="my-2 leading-7">오늘 비교한 결과의 부족한 부분과 고칠 요청을 써 보세요. “예시 A는 ___ 조건을 놓쳤어요. ___로 다시 요청하고, 결과의 ___을 확인해요.”</p><Textarea id="reflection" className="min-h-28 text-base md:text-base" maxLength={1000} value={reflection} onChange={e => setReflection(e.target.value)} /><p className="mt-1 text-sm text-muted-foreground">{reflection.trim().length} / 1000자 · 10자 이상</p></div></div>;
}

function PlayComparison({ choices }: { choices: boolean[] }) {
  const before = lessonFourExamples([false, false, false]);
  const after = lessonFourExamples(choices);
  return <section className="space-y-5 rounded-2xl border-2 border-primary/30 p-5" aria-labelledby="play-comparison">
    <h3 id="play-comparison" className="text-xl font-black">조건을 찾아 두 결과 비교하기</h3>
    <p className="leading-7">아래는 수업용으로 준비한 예시예요. 실제 AI 답을 생성한 것은 아니에요. 조건을 넣었어도 결과가 맞는지는 사람이 확인해야 해요.</p>
    <div className="rounded-xl bg-secondary p-4"><h4 className="font-bold">내가 더 구체적으로 만든 요청</h4><p className="mt-2 leading-7">{after.request}</p></div>
    <PlayTable title="예시 A · 추가 조건을 넣기 전" example={before} />
    <PlayTable title="예시 B · 선택한 조건을 넣은 뒤" example={after} />
    <ul className="space-y-3">{after.comparisons.map(row => <li key={row.condition} className="rounded-xl bg-muted p-4 leading-7"><strong>{row.condition}</strong><p>A에서 찾을 부분: {row.before}</p><p>B에서 비교할 부분: {row.after}</p></li>)}</ul>
    <p className="leading-7">짝과 선택한 조건 두 개를 결과 속 말에 연결해 설명해요. A에서 빠진 조건 하나를 골라 다음 단계에서 수정 요청을 말해 보세요. 더 해보기: 조건 하나만 바꾸고 B에서 달라질 부분을 먼저 예상해요.</p>
  </section>;
}
function PlayTable({ title, example }: { title: string; example: ReturnType<typeof lessonFourExamples> }) {
  return <table className="w-full table-fixed border-collapse text-left leading-7">
    <caption className="mb-2 text-left font-black">{title}</caption>
    <thead><tr><th scope="col" className="w-1/4 border bg-muted p-3">놀이</th><th scope="col" className="border bg-muted p-3">방법·장소{example.reasons ? '·이유' : ''}</th></tr></thead>
    <tbody>{example.rows.map(row => <tr key={row.name}><th scope="row" className="break-words border p-3 align-top">{row.name}</th><td className="break-words border p-3"><p>{row.method}</p><p>장소: {row.place}</p>{row.reason && <p>이유: {row.reason}</p>}</td></tr>)}</tbody>
  </table>;
}
