'use client';

import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { clueItems, detailOptions, questions, revisionItems, type LessonFourActivities } from '@/lib/lesson-four';

type Props = { step: number; activities: LessonFourActivities; update: (patch: Partial<LessonFourActivities>) => void; reflection: string; setReflection: (value: string) => void };

export function LessonFourContent({ step, activities: a, update, reflection, setReflection }: Props) {
  if (step === 1) return <div className="mt-6 space-y-6"><p className="leading-8">AI에게 부탁할 때는 짧기만 한 말보다, 내가 원하는 것을 알아듣기 쉽게 알려 주는 말이 좋아요. 두 요청 중 더 이해하기 쉬운 것을 골라 보세요.</p><fieldset className="space-y-3"><legend className="mb-3 font-bold">학교 축제 포스터 아이디어를 부탁한다면?</legend>{['포스터 아이디어를 멋지게 만들어 줘.', '6학년 학교 축제 포스터 아이디어를 3개, 각각 제목과 색깔을 표로 제안해 줘.'].map((s, i) => <label key={s} className="flex cursor-pointer items-start gap-3 rounded-xl border p-4 leading-7"><input className="mt-2" type="radio" name="opening" checked={a.opening === i} onChange={() => update({ opening: i })} />{s}</label>)}</fieldset>{a.opening !== null && <p className="rounded-xl bg-secondary p-4 leading-7">맞아요. 목표와 대상, 개수와 결과 모양까지 말하면 AI가 내 생각을 더 잘 이해할 수 있어요.</p>}</div>;
  if (step === 2) return <div className="mt-6 space-y-5"><p className="leading-7">좋은 지시에는 네 가지 단서가 있어요. 각 문장이 어떤 단서인지 골라 보세요.</p><div className="space-y-4">{clueItems.map((item, i) => <fieldset key={item.text} className="rounded-2xl border p-4"><legend className="px-1 font-bold">단서 {i + 1}</legend><p className="mb-3 leading-7">{item.text}</p><div className="flex flex-wrap gap-2">{['목표', '상황', '조건', '결과 형식'].map((label, j) => <label key={label} className="flex cursor-pointer items-center gap-2 rounded-xl border px-3 py-3"><input type="radio" name={`clue-${i}`} checked={a.clueChoices[i] === j} onChange={() => update({ clueChoices: a.clueChoices.map((v, k) => k === i ? j : v), cluesChecked: false })} />{label}</label>)}</div>{a.cluesChecked && <p className="mt-3 rounded-xl bg-secondary p-3">{a.clueChoices[i] === item.answer ? '정답이에요!' : `정답은 ‘${item.label}’이에요.`}</p>}</fieldset>)}</div><Button disabled={a.clueChoices.some(v => v === null)} onClick={() => update({ cluesChecked: true })}>단서 확인</Button>{a.cluesChecked && <p role="status" className="font-bold">{clueItems.filter((x, i) => a.clueChoices[i] === x.answer).length} / 4개 정답</p>}</div>;
  if (step === 3) return <div className="mt-6 space-y-5"><p className="leading-7">“우리 반 쉬는 시간 놀이를 추천해 줘.”라는 요청에 어떤 조건을 더하면 좋을까요? 두 가지 이상을 골라 결과를 확인해 보세요.</p><div className="space-y-3">{detailOptions.map((s, i) => <label key={s} className="flex cursor-pointer items-center gap-3 rounded-xl border p-4 leading-7"><input type="checkbox" checked={a.detailChoices[i]} onChange={e => update({ detailChoices: a.detailChoices.map((v, k) => k === i ? e.target.checked : v), detailResultChecked: false })} />{s}</label>)}</div><Button disabled={a.detailChoices.filter(Boolean).length < 2} onClick={() => update({ detailResultChecked: true })}>결과 비교하기</Button>{a.detailResultChecked && <div role="status" className="rounded-2xl bg-secondary p-4 leading-7"><p className="font-bold">좋은 조건을 넣었어요!</p><p className="mt-2">“6학년이 이해하기 쉽게, 우리 동네의 안전한 장소만, 이유를 한 줄씩 덧붙여서 추천해 줘.”처럼 말하면 결과를 비교하고 고르기 쉬워요.</p></div>}</div>;
  if (step === 4) return <div className="mt-6 space-y-5"><p className="leading-7">첫 결과가 부족하면 무엇이 부족한지 구체적으로 말하고 다시 요청해요. 상황에 알맞은 수정 요청을 골라 보세요.</p><div className="space-y-4">{revisionItems.map((item, i) => <fieldset key={item.text} className="rounded-2xl border p-4"><legend className="px-1 font-bold">상황 {i + 1}</legend><p className="mb-3 leading-7">{item.text}</p><div className="space-y-2">{item.options.map((s, j) => <label key={s} className="flex cursor-pointer items-start gap-3 rounded-xl bg-muted/60 p-3 leading-7"><input className="mt-2" type="radio" name={`revision-${i}`} checked={a.revisionChoices[i] === j} onChange={() => update({ revisionChoices: a.revisionChoices.map((v, k) => k === i ? j : v), revisionsChecked: false })} />{s}</label>)}</div>{a.revisionsChecked && <p className="mt-3 rounded-xl bg-secondary p-3">{a.revisionChoices[i] === item.answer ? '정답이에요!' : '부족한 점을 더 구체적으로 말해 보세요.'}</p>}</fieldset>)}</div><Button disabled={a.revisionChoices.some(v => v === null)} onClick={() => update({ revisionsChecked: true })}>수정 요청 확인</Button>{a.revisionsChecked && <p role="status" className="font-bold">{revisionItems.filter((x, i) => a.revisionChoices[i] === x.answer).length} / 3개 정답</p>}</div>;
  return <div className="mt-6 space-y-6">{questions.map((q, i) => <fieldset key={q.title} className="rounded-2xl border p-4"><legend className="px-1 font-bold">퀴즈 {i + 1}</legend><p className="mb-3 font-bold leading-7">{q.title}</p><div className="space-y-3">{q.options.map((s, j) => <label key={s} className="flex cursor-pointer items-start gap-3 rounded-lg bg-muted/60 p-3 leading-7"><input className="mt-2" type="radio" name={`quiz-${i}`} checked={a.answers[i] === j} onChange={() => update({ answers: a.answers.map((v, k) => k === i ? j : v), quizChecked: false })} />{s}</label>)}</div>{a.quizChecked && <p className="mt-3 rounded-xl bg-secondary p-3 leading-7">{a.answers[i] === q.answer ? '정답이에요! ' : '다시 생각해 봐요. '}{q.tip}</p>}</fieldset>)}<Button disabled={a.answers.some(v => v === null)} onClick={() => update({ quizChecked: true })}>퀴즈 확인</Button>{a.quizChecked && <p role="status" className="font-bold">{questions.filter((q, i) => a.answers[i] === q.answer).length} / 3문항 정답</p>}<div><label htmlFor="ownPrompt" className="font-black">나만의 안전한 지시</label><p className="my-2 leading-7">개인정보 없이, 목표·상황·조건·결과 형식 중 두 가지 이상을 넣어 AI에게 부탁하는 문장을 써 보세요.</p><Textarea id="ownPrompt" className="min-h-32 text-base md:text-base" maxLength={1000} value={a.ownPrompt} onChange={e => update({ ownPrompt: e.target.value })} /><p className="mt-1 text-sm text-muted-foreground">{a.ownPrompt.trim().length} / 1000자 · 20자 이상</p></div><div><label htmlFor="reflection" className="font-black">오늘의 성찰</label><p className="my-2 leading-7">AI의 첫 결과가 부족할 때 내가 할 일을 써 보세요.</p><Textarea id="reflection" className="min-h-28 text-base md:text-base" maxLength={1000} value={reflection} onChange={e => setReflection(e.target.value)} /><p className="mt-1 text-sm text-muted-foreground">{reflection.trim().length} / 1000자 · 10자 이상</p></div></div>;
}
